### ISSUE TITLE
404 Response from tempo-timesheets API

### ISSUE THREAD

**Issue by kshaa** [molsm/jira-report-web-ui-improved#1]
Judging by the fact that the [API is tagged "Experimental"](http://developer.tempo.io/doc/timesheets/api/rest/latest/#848933329), I'd guess that they changed something.
Maybe this is just a temporary issue though.

This throws a 404 - https://github.com/molsm/jira-report-web-ui-improved/blob/87ef553923f8265b258d9bdd54f1f3719b29908f/src/server/controller/jira.js#L5

**Comment by molsm** [comment]
Resolved. Now authentication will be through Tempo token
